### ISSUE TITLE
Need a LICENSE file added to the repo

### ISSUE THREAD

**Issue by mightynimble** [Novetta/CLAVIN-rest#12]
As a contributor to NASA organization in github (https://github.com/orgs/nasa/people?utf8=%E2%9C%93&query=bo%20sun), we forked this project and attempt to use it as a backend service for spatial and temporal parsing for NASA's Earthdata Search (https://github.com/nasa/earthdata-search). We saw the CLAVIN repo uses an apache LICENSE file whereas this repo doesn't have a LICENSE.

Could you add a LICENSE file to this repo at your convenience so that we can formally fork the project and develop off from the fork on behalf of NASA? It will be the best if the same apache LICENSE can be added here. 

Thanks a lot!
Bo

**Comment by jglesner-novetta** [comment]
Apologies for not following up in 2016. We are now updating clavin-rest and clavin; and we are adding a license to this repo shortly.
