### ISSUE TITLE
[Question] Using different Gazetteer Index, e.g OpenStreetMap Nonimatim or custom index

### ISSUE THREAD

**Issue by zocoi** [Novetta/CLAVIN-rest#13]
Hi

I'd love to get instructions or guides how to change the CLAVIN Geonames gazetteer index for something else which is more granular or more hyper local

We can use our own location db or download the entire OSM which supports cities, neighborhoods and exact locations then build new Lucene index for different location type.

The datasize will be much bigger compared with Geonames ~330MB but I think embedded Lucene should be able to handle it. Any hint to where to start?

**Comment by jglesner-novetta** [comment]
Apologies for not following up in 2017. We are now updating clavin-rest and clavin.  Since this is a question that seems to pertain more to CLAVIN, if you still need support, please repost in the https://github.com/Novetta/CLAVIN project.
