### ISSUE TITLE
Can not build do to internal references are being used

### ISSUE THREAD

**Issue by shawnwhit** [Novetta/CLAVIN-rest#15]
Failed to build do to it is looking for a POM that no longer is present.

http://nexus.bericotechnologies.com/content/repositories/snapshots/com/yammer/dropwizard/dropwizard-parent/0.6.2/dropwizard-parent-0.6.2.pom

**Comment by jglesner-novetta** [comment]
Updating CLAVIN-rest to Spring boot. This issue will be resolved in the new release.
