### ISSUE TITLE
Installation problems (Release not found)

### ISSUE THREAD

**Issue by PietroPasotti** [Novetta/CLAVIN-rest#4]
1) it seems to me that, in order to use the python API, I need a clavin-rest server up and running. (Although I found no documentation supporting this)

2) the problem is: there is no release of clavin-rest online, at least here on github. Running 
curl -L https://github.com/Berico-Technologies/CLAVIN-rest/releases/download/0.2.0/clavin-rest-0.2.0.jar -o clavin-rest.jar
as suggested in the readme, results in a 'clavin-rest.jar' file which actually is a text file containing only the text "{"error":"Not Found"}"
and in fact there seems to be no file at all at the specified address. Where can I find the .jar?

**Comment by vlurgio** [comment]
There is still no release at the location pointed to in the readme btw

**Comment by jglesner-novetta** [comment]
We will be releasing a new version of CLAVIN-rest in the near future, which will point to an updated CLAVIN 3.0.
