### ISSUE TITLE
CLAVIN-rest failed to successfully build maven packages .

### ISSUE THREAD

**Issue by s4sarath** [Novetta/CLAVIN-rest#6]
Hi,

mvn package 

failed for CLAVIN-rest . It fails to download the following dependencies.

BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.055 s
[INFO] Finished at: 2015-01-29T17:53:37+05:30
[INFO] Final Memory: 9M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project clavin-rest: Could not resolve dependencies for project com.bericotech:clavin-rest:jar:0.2.0: The following artifacts could not be resolved: com.sun.jersey:jersey-server:jar:1.17.1, asm:asm:jar:3.1, com.sun.jersey:jersey-servlet:jar:1.17.1, com.yammer.metrics:metrics-core:jar:2.2.0, com.yammer.metrics:metrics-servlet:jar:2.2.0, com.yammer.metrics:metrics-jetty:jar:2.2.0, com.yammer.metrics:metrics-logback:jar:2.2.0, com.yammer.metrics:metrics-jersey:jar:2.2.0, com.yammer.metrics:metrics-annotation:jar:2.2.0, com.fasterxml.jackson.core:jackson-databind:jar:2.1.4, com.fasterxml.jackson.core:jackson-annotations:jar:2.1.4, com.fasterxml.jackson.core:jackson-core:jar:2.1.4, com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.1.4, com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.1.4, com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.1.4, com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.1.2, net.sourceforge.argparse4j:argparse4j:jar:0.4.0, org.slf4j:slf4j-api:jar:1.7.4, org.slf4j:jul-to-slf4j:jar:1.7.4, ch.qos.logback:logback-core:jar:1.0.10, ch.qos.logback:logback-classic:jar:1.0.10, org.slf4j:log4j-over-slf4j:jar:1.7.4, org.eclipse.jetty:jetty-server:jar:8.1.10.v20130312, org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016, org.eclipse.jetty:jetty-continuation:jar:8.1.10.v20130312, org.eclipse.jetty:jetty-servlet:jar:8.1.10.v20130312, org.eclipse.jetty:jetty-security:jar:8.1.10.v20130312, org.eclipse.jetty:jetty-http:jar:8.1.10.v20130312, org.eclipse.jetty:jetty-io:jar:8.1.10.v20130312, org.eclipse.jetty:jetty-util:jar:8.1.10.v20130312, org.hibernate:hibernate-validator:jar:4.3.1.Final, javax.validation:validation-api:jar:1.0.0.GA, org.jboss.logging:jboss-logging:jar:3.1.0.CR2, com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.1.2, com.bazaarvoice.dropwizard:dropwizard-configurable-assets-bundle:jar:0.1.11, com.bericotech:clavin-nerd:jar:2.0.0, edu.stanford.nlp:stanford-corenlp:jar:3.4.1, com.io7m.xom:xom:jar:1.2.10, xml-apis:xml-apis:jar:1.3.03, xerces:xercesImpl:jar:2.8.0, xalan:xalan:jar:2.7.0, de.jollyday:jollyday:jar:0.4.7, javax.xml.bind:jaxb-api:jar:2.2.7, com.googlecode.efficient-java-matrix-library:ejml:jar:0.23, javax.json:javax.json-api:jar:1.0, com.bericotech:clavin:jar:2.0.0: Could not transfer artifact com.sun.jersey:jersey-server:jar:1.17.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Unknown host repo.maven.apache.org -> [Help 1]

How to edit pom.xml to avoid this. Any suggestions ?

**Comment by tlpinney** [comment]
@s4sarath 

Can you post what version of maven you are using as well as the system your building on? 
Is there an issue with your dns? 

repo.maven.apache.org: Unknown host repo.maven.apache.org 

I tested it recently and it is working for me.

**Comment by chuckdudley** [comment]
If you are unable to contact that repo server it will not build. Verify
connectivity to that host name. If it does not respond you will have to
mirror that repo server.
